import { Header } from '@/shared/components/shared';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'NextPizza | Корзина',
  description: 'Generated by AlexandrKabana',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Header hasSearch={false} className="border-gray-200" />
      {children}
    </main>
  );
}
